### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by dodekaeder** [hwz/chirp#2]
Hi,
i'm totally noobie, but trying to get into mean development. I'm following your
tutorial (copy/paste) to get an understanding for this issue but running into a 404
with advanced rest client.
I completely covered your way trough the tutorial...

I did build it on a remote ubuntu 14 vserver (which i think maybe the well of 404) and get

```
<h1>Big Bad Thing! but allready workin'...</h1>
<h2>404</h2>
<pre>Error: Not Found
   at /home/user/apps/chirp/Start/app.js:31:13
   at Layer.handle [as handle_request] (/home/user/apps/chirp/Start/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/home/user/apps/chirp/Start/node_modules/express/lib/router/index.js:302:13)
   at /home/user/apps/chirp/Start/node_modules/express/lib/router/index.js:270:7
   at Function.proto.process_params (/home/user/apps/chirp/Start/node_modules/express/lib/router/index.js:321:12)
   at next (/home/user/apps/chirp/Start/node_modules/express/lib/router/index.js:261:10)
   at /home/user/apps/chirp/Start/node_modules/express/lib/router/index.js:603:15
   at next (/home/user/apps/chirp/Start/node_modules/express/lib/router/index.js:246:14)
   at Function.proto.handle (/home/user/apps/chirp/Start/node_modules/express/lib/router/index.js:166:3)
   at router (/home/user/apps/chirp/Start/node_modules/express/lib/router/index.js:35:12)</pre>
```

i allready tried to get the clue and manged to modify issues.net (relpaces $message with my funny little line) to see if i'm entering the script anyway....

you see i'm just making baby steps but need some help to get on my feets :D 

hopefully you got a clue

ciao
dodekaeder

**Comment by newcreator** [comment]
make sure you make request for http://localhost:3000/api/posts, not just http://localhost:3000/posts.
at least, that's why i've got this error.
